// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TftTracker.Data;

#nullable disable

namespace TftTracker.Migrations
{
    [DbContext(typeof(TftContext))]
    [Migration("20211124094226_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TftTracker.Data.Entities.Summoner", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("accountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("profileIconId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("puuid")
                        .HasColumnType("TEXT");

                    b.Property<long>("revisionDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("summonerLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Summoners");
                });
#pragma warning restore 612, 618
        }
    }
}
